// Package codes documents every diagnostic code (`veld explain CODE`).
package codes

// Info describes one diagnostic code.
type Info struct {
	Title   string `json:"title"`
	Explain string `json:"explain"`
}

// All maps codes to their documentation. Keep in sync with the compiler; the
// test suite checks that every code the compiler emits is listed here.
var All = map[string]Info{
	"E101": {"lexical error", "The source contains a character or literal Veld does not understand. Common causes: `&&`, `||`, `!`, `;` (use `and`, `or`, `not`, newlines) or single-quoted strings."},
	"E102": {"bad escape", `Valid escapes in "..." strings are \n \t \r \\ \" \$ \0. Use """raw strings""" for text with many backslashes or quotes.`},
	"E103": {"bad interpolation", `Interpolation is ${expr}. The expression may not contain string literals; bind them with let first. Write \$ for a literal dollar sign before {.`},
	"E104": {"unexpected token", "The parser expected a different token here. Read the message for what was expected."},
	"E105": {"expected end of line", "Each statement goes on its own line. Block bodies start on the line after their header (`if cond`, `match x`, `fn f() -> T`) and end with `end <keyword>`."},
	"E106": {"misplaced use", "`use` declarations must come before all other declarations."},
	"E107": {"expected declaration", "Top-level items are `fn`, `type`, `record`, `test` and `use`. Veld has no global variables; use a zero-argument function."},
	"E108": {"missing annotation", "Function parameters and return types are always annotated. Use `-> Unit` for functions that return nothing."},
	"E109": {"unknown effect", "Effects are: io, fs, net, env, time, rand, proc, state."},
	"E110": {"block closer", "Every block ends with `end` plus the keyword that opened it: end fn, end if, end match, end for, end while, end type, end record, end test. A mismatch means a block was not closed."},
	"E111": {"type declaration syntax", "Sum types list variants with `case`:\n  type Shape\n    case Circle(radius: Float)\n    case Empty\n  end type"},
	"E112": {"type argument syntax", "Type arguments use square brackets: List[Int], Map[Str, Int], Option[T]."},
	"E113": {"assignment syntax", "New bindings use `let` (immutable) or `var` (mutable). Reassign a var with `set x = value`. Records are immutable: build a copy with `Point{..p, x: 1}`."},
	"E114": {"pipe syntax", "`a |> f(b)` means `f(a, b)`. The right side must be a call."},
	"E115": {"operator grouping", "`and`/`or` cannot be mixed without parentheses, and comparisons cannot be chained."},
	"E116": {"named argument syntax", "Named arguments use a colon: f(x, width: 3)."},
	"E117": {"record literal syntax", "Record literals name every field: User{name: \"a\", age: 3}. Use `..base` first to copy the remaining fields."},
	"E118": {"integer literal too large", "Int is a signed 64-bit integer."},
	"E119": {"unsupported construct", "Veld has no null (use Option), no self/this (pass values explicitly), no tuples (use a record)."},
	"E120": {"function syntax", "Named functions exist only at the top level. Lambdas are `fn(x) => expr` or a multi-line body ending with `end fn`."},
	"E121": {"else position", "`else` must be the last branch of an if."},
	"E122": {"match syntax", "Arms are `case pattern => expr` or `case pattern` followed by an indented block. Guards: `case x if x > 0 => ...`."},
	"E123": {"for syntax", "`for x in items` binds one variable. For indices: `for i in list.range(0, list.len(xs))`."},
	"E124": {"pattern syntax", "Patterns: _, name, literals (Int, Str, Bool), Ctor(p1, p2), [], [a, b], [head, ..rest], [..init, last], and alternatives p1 | p2."},
	"E201": {"naming convention", "Types, variants and type parameters are PascalCase; everything else is snake_case. Names are ASCII."},
	"E202": {"duplicate definition", "A name may be defined once per module. Constructor names are module-wide."},
	"E203": {"unknown type", "Built-in types: Int, Float, Bool, Str, Unit, List[T], Map[K, V], Option[T], Result[T, E], Json. Types from other modules are qualified: http.Request."},
	"E204": {"shadowing", "Veld forbids rebinding a name that is already visible in the function. Pick a new name, or use var + set."},
	"E205": {"unknown name", "The name is not defined here. Standard library functions are called through their module after importing it: `use std.list` then `list.len(xs)`."},
	"E206": {"not public", "Only `pub` declarations can be used from other modules."},
	"E207": {"extern outside std", "`extern fn` declares a natively implemented function and is reserved for the standard library."},
	"E301": {"type mismatch", "The value's type differs from the type required here. Veld never converts implicitly: use math.to_float, math.round, \"${x}\", Some(x) etc."},
	"E302": {"wrong number of type arguments", "Generic types need all their type arguments: List[Int], Map[Str, Int]."},
	"E303": {"argument naming", "Calls with 3 or more arguments must name every argument after the first: str.replace(s, old: \"a\", new: \"b\"). Positional arguments come before named ones."},
	"E304": {"wrong number of arguments", "The call passes too many or too few arguments."},
	"E305": {"block needs a value", "The last line of a block is its value. A block whose value is used must end with an expression."},
	"E306": {"assignment to immutable", "`let` bindings, parameters and pattern variables cannot be reassigned. Declare with `var` to use `set`."},
	"E307": {"expect outside test", "`expect` is only allowed in `test` blocks."},
	"E308": {"unused value", "An expression statement produced a value that is thrown away. Veld values are immutable, so `list.push(xs, 1)` alone does nothing: write `set xs = list.push(xs, 1)`, or `let _ = f()` to discard deliberately."},
	"E309": {"cannot interpolate function", "Functions have no string form."},
	"E310": {"operator type error", "+ works on Int, Float, Str and List; - * / % on Int and Float; < <= > >= on Int, Float and Str; == and != on any non-function type. Both sides must have the same type."},
	"E311": {"invalid map key", "Map keys cannot be functions."},
	"E312": {"not iterable", "`for` iterates over a List. Use map.keys(m), str.chars(s) or list.range(a, b)."},
	"E313": {"missing return value", "`return` needs a value unless the function returns Unit."},
	"E314": {"break outside loop", "`break` and `continue` only work inside for/while loops (not across lambda boundaries)."},
	"E315": {"constructor usage", "Constructors with fields are called: Circle(1.0). Constructors without fields are written bare: None."},
	"E316": {"module used as value", "A module name can only be used to access members: io.print(...)."},
	"E317": {"unknown field", "The record has no such field, or the type is not a record. Veld has no methods: call module functions instead, e.g. list.len(xs) or xs |> list.len()."},
	"E318": {"cannot infer type", "Inference did not have enough information. Add a type annotation to the lambda parameter or binding."},
	"E319": {"not callable", "Only functions can be called."},
	"E320": {"not orderable", "Sorting and min/max need Int, Float or Str values. Use list.sort_by with a key function."},
	"E321": {"record literal on sum type", "Sum types are built with their constructors, not with {...}."},
	"E322": {"missing fields", "Record literals must set every field (or start with ..base)."},
	"E323": {"lambda arity", "The lambda's parameter count differs from the function type expected here."},
	"E324": {"if without else", "An if used as a value needs an else branch."},
	"E325": {"invalid ?", "`x?` unwraps Ok/Some and returns Err/None from the enclosing function, which must return a Result with the same error type (or an Option)."},
	"E401": {"undeclared effect", "Functions declare the effects they perform: `fn main() -> Unit uses io, fs`. Callers of an effectful function must declare its effects too. Pure functions declare none."},
	"E402": {"effect not permitted", "A function value performing effects was passed where the parameter's type does not allow them."},
	"E501": {"non-exhaustive match", "Every possible value must be matched. Add the missing case, or a final `case _ =>` arm."},
	"E502": {"duplicate pattern binding", "A name can be bound once per pattern."},
	"E503": {"constructor pattern arity", "Match every field of the constructor: `case Rect(w, h)`; use `_` for fields you ignore."},
	"E504": {"binding in or-pattern", "`case A | B =>` alternatives cannot bind variables; use separate cases."},
	"E507": {"case arity in multi-value match", "`match a, b` needs exactly one pattern per value in every `case`: `case Idle, Start =>`. Use `_` for values you do not care about."},
	"E508": {"too many match values", "A `match` can list at most 4 values; group related values in a record."},
	"E509": {"several patterns in a single-value match", "A `case` lists several patterns only when the `match` lists several values: write `match a, b` and `case p, q =>`."},
	"E510": {"incomplete record pattern", "A record pattern must mention every field or end with `..`: `case User{name, ..} =>`. This keeps a case honest when the record gains a field."},
	"E511": {"unknown record or field in a pattern", "Record patterns name a record type and its fields: `case User{name, age: 3} =>`. Check the spelling; sum types are matched by their variants."},
	"E601": {"unknown module", "Import modules at the top of the file: `use std.list` or `use util.text` (the file util/text.veld next to the entry file)."},
	"E602": {"import cycle", "Modules cannot import each other in a cycle."},
	"E603": {"module not found", "The module file does not exist. Local modules are resolved relative to the entry file's directory."},
	"W201": {"unused variable", "The binding is never read. Prefix it with _ if that is intentional."},
	"W202": {"Unit binding", "The binding holds Unit, which is almost always a mistake."},
	"W501": {"unreachable case", "Earlier cases already cover this one."},
	"H001": {"typed hole", "`???` is a placeholder expression (a typed hole). The checker reports the type it must have and the variables in scope. Reaching one at runtime is an error."},
	"R101": {"integer overflow", "Int arithmetic that overflows 64 bits stops the program."},
	"R102": {"division by zero", "Integer division or remainder by zero."},
	"R201": {"contract violation", "A `requires` or `ensures` clause evaluated to false."},
	"R300": {"invalid argument", "A standard library function received an argument it cannot handle; the message says which."},
	"R301": {"hole reached", "Execution reached a `???` hole."},
	"R302": {"panic", "The program called panic(...)."},
	"R303": {"no case matched", "A match fell through; only possible when all remaining cases have guards."},
	"R401": {"effect not granted", "The program performed an effect that the runner did not grant (see `veld run --deny`)."},
	"R501": {"stack overflow", "Recursion went deeper than 10000 calls."},
	"T001": {"expectation failed", "An `expect` in a test was false. For comparisons both sides are shown."},
}
